name: 'Entrepreneur  '
favicon: null
layout_spectrum: 0.04778011096641421
typography_spectrum: 0.41278559155762196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8788193590007722
  lightness: 0.8763812757097185
  saturation: 0.6277655372396111
  rhythmicContrast: 0.6514682357665151
purpose: []
